### ISSUE TITLE
Dropped from CRAN

### ISSUE THREAD

**Issue by natecobb** [edgararuiz/connections#11]
Looks like the package was dropped from CRAN a couple of weeks ago for unaddressed check failures. I use the package for teaching to wrap RPostgres and a couple of students ran into install problems. Would be nice to have it on CRAN despite the experimental status, although obviously installing from GitHub works.

**Comment by jjesusfilho** [comment]
I also use this package for teaching and to motivate people to not put more GUI clients in their computers. It would be nice if it went back to CRAN.

**Comment by GitHunter0** [comment]
I wonder why this package was abandoned... it was quite useful.

**Comment by edgararuiz** [comment]
Hi everyone, I resubmitted the package to CRAN, and it was accepted this morning! https://cloud.r-project.org/web/packages/connections/index.html
